version: "3.9"
services:
  dotnet-interactive:
    build:
      context: .
      dockerfile: Dockerfile
    image: dotnet-interactive
    container_name: dotnet-interactive
    user: 1000:1000
    volumes:
      - /home/layez/dotnet-interactive/work:/home/jovyan/work
    environment:
      - TZ=Asia/Shanghai
      - JUPYTER_ENABLE_LAB=yes
    ports:
      - 9888:8888
    restart: unless-stopped